commit

diff --git a/.github/workflows/pre-release.yaml b/.github/workflows/pre-release.yaml
--- a/.github/workflows/pre-release.yaml
+++ b/.github/workflows/pre-release.yaml
@@ -17,7 +17,7 @@ jobs:
     steps:
       - name: Check if release exists
         id: check-release
-        uses: actions/github-script@v7
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         with:
           script: |
             try {
@@ -40,7 +40,7 @@ jobs:
               }
             }
           github-token: ${{ secrets.GITHUB_TOKEN }}
-      - uses: actions/create-release@v1
+      - uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
         if: ${{ steps.check-release.outputs.release-exists == 'false'}}
         id: create-release
         env:
@@ -51,17 +51,195 @@ jobs:
           draft: true
           prerelease: true
 
+  build-packages:
+    needs:
+      - create-release
+    runs-on: ubuntu-22.04
+    outputs:
+      package_version: ${{ steps.metadata.outputs.PACKAGE_VERSION }}
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 1
+
+      - name: Set up Go
+        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
+        with:
+          go-version: '1.23.x'
+
+      - name: setup GPG
+        uses: aerospike/shared-workflows/.github/actions/setup-gpg@dda8173aca1f1e73f95267572a7d3849cd00f1b8 # v1.0.0
+        with:
+          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
+          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
+          gpg-key-pass: ${{ secrets.GPG_PASS }}
+          gpg-key-name: 'aerospike-inc'
+
+      - name: Install Dependencies
+        run: |
+          go install "github.com/goreleaser/nfpm/v2/cmd/nfpm@latest"
+          sudo apt-get update && sudo apt-get install -y dpkg-dev
+
+      - name: Get Metadata
+        id: metadata
+        run: |
+          PACKAGE_VERSION=$(cat VERSION)
+          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
+          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
+          echo "PACKAGE_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
+
+      - name: Login to JFrog
+        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 #v4.5.11
+        env:
+          JF_URL: ${{ vars.ARTIFACTORY_URL }}
+          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
+          JF_PROJECT: ${{ vars.JFROG_CLI_BUILD_PROJECT }}
+
+      - name: Build Packages
+        run: |
+          make packages
+
+      - name: Find files matching "*.rpm" "*.deb""
+        run: |
+          RPM_ASSET_LIST=$(find . -type f \( -name "*.rpm" \) | tr '\n' ',')
+          DEB_ASSET_LIST=$(find . -type f \( -name "*.deb" \) | tr '\n' ',')
+          echo "RPM_ASSET_LIST=$RPM_ASSET_LIST" >> $GITHUB_ENV
+          echo "DEB_ASSET_LIST=$DEB_ASSET_LIST" >> $GITHUB_ENV
+
+      - name: Sign RPM Packages
+        env:
+          GPG_TTY: no-tty
+          GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
+
+        run: |
+          IFS=',' read -r -a asset_array <<< "$RPM_ASSET_LIST"
+          for file in "${asset_array[@]}"; do
+            echo "file is: ${file}"
+            rpm --addsign "${file}"
+            echo "here"
+            OUTPUT=$(rpm --checksig "${file}")
+            if [[ "$OUTPUT" =~ 'digests signatures OK' ]]; then
+              echo "Successfully GPG Signed $file"
+            else
+              echo "$OUTPUT"
+              echo "GPG Signing $file has failed."
+              exit 1
+            fi
+          done
+
+      - name: Sign DEB Packages
+        env:
+          GPG_TTY: no-tty
+          GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
+        run: |
+          IFS=',' read -r -a asset_array <<< "$DEB_ASSET_LIST"
+          for file in "${asset_array[@]}"; do
+            dpkg-sig --sign builder "${file}"
+            OUTPUT=$(dpkg-sig --verify "${file}")
+            if [[ "$OUTPUT" =~ 'GOODSIG _gpgbuilder' ]]; then
+              echo "Successfully GPG Signed $file"
+            else
+              echo "$OUTPUT"
+              echo "GPG Signing $file has failed."
+              exit 1
+            fi
+           done
+
+      - name: Create checksums
+        run: |
+          make checksums
+          CHECKSUMS_ASSET_LIST=$(find . -type f \( -name "*.sha256" \) | tr '\n' ',')
+          echo "CHECKSUMS_ASSET_LIST=$CHECKSUMS_ASSET_LIST" >> $GITHUB_ENV
+
+      - name: Sign checksums
+        env:
+          GPG_TTY: no-tty
+          GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
+        run: |
+          IFS=',' read -r -a asset_array <<< "$CHECKSUMS_ASSET_LIST"
+          for file in "${asset_array[@]}"; do
+            gpg --detach-sign --no-tty --batch --yes --output "${file}.asc" --passphrase "$GPG_PASSPHRASE" "${file}"
+            gpg --verify "${file}.asc" "${file}" &>/dev/null
+            RETURN_CODE=$?
+            if [ ! "$RETURN_CODE" = 0 ]; then
+              echo "GPG Signing of $file has failed."
+              exit 1
+            else
+              echo "Successfully GPG Signed $file"
+            fi
+          done
+          ASC_ASSET_LIST=$(find . -type f \( -name "*.asc" \) | tr '\n' ',')
+          echo "ASC_ASSET_LIST=$ASC_ASSET_LIST" >> $GITHUB_ENV
+
+      - name: Upload Assets to Github Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          upload_url="$(echo "${{ needs.create-release.outputs.upload_url }}" | sed 's/\(assets\).*/\1/')"
+          ASSET_LIST="${RPM_ASSET_LIST%,},${DEB_ASSET_LIST%,},${CHECKSUMS_ASSET_LIST%,},${ASC_ASSET_LIST%,}"
+          ASSET_LIST="${ASSET_LIST#,}"
+          IFS=',' read -r -a asset_array <<< "$ASSET_LIST"
+          for file in "${asset_array[@]}"; do
+            curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -H "Content-Type: $(file -b --mime-type $file)" \
+            "$upload_url?name=$(basename $file)" \
+            --data-binary "@$file"
+          done
+
+      - name: Upload RPM Packages to Jfrog
+        env:
+          JF_PROJECT: ${{ vars.JFROG_CLI_BUILD_PROJECT }}
+          ARTIFACTORY_RPM_DEV: ${{ vars.ARTIFACTORY_RPM_DEV }}
+
+        run: |
+          IFS=',' read -r -a asset_array <<< "$RPM_ASSET_LIST"
+          for file in "${asset_array[@]}"; do
+            arch=$(rpm -q --qf "%{ARCH}" -p "$file")
+
+            jfrog rt upload "$file" "$ARTIFACTORY_RPM_DEV/$PACKAGE_NAME/$PACKAGE_VERSION/$(basename $file)" \
+            --build-name=$PACKAGE_NAME-rpm --build-number=$PACKAGE_VERSION \
+            --target-props "rpm.distribution=stable;rpm.component=main;rpm.architecture=$arch"
+          done
+
+          jfrog rt build-collect-env "$PACKAGE_NAME-rpm" "$PACKAGE_VERSION"
+          jfrog rt build-add-git  "$PACKAGE_NAME-rpm" "$PACKAGE_VERSION"
+          jfrog rt build-publish  "$PACKAGE_NAME-rpm" "$PACKAGE_VERSION"
+
+      - name: Upload DEB Packages to Jfrog
+        env:
+          JF_PROJECT: ${{ vars.JFROG_CLI_BUILD_PROJECT }}
+          ARTIFACTORY_DEB_DEV: ${{ vars.ARTIFACTORY_DEB_DEV }}
+        run: |
+          IFS=',' read -r -a asset_array <<< "$DEB_ASSET_LIST"
+          for file in "${asset_array[@]}"; do
+            arch=$(dpkg --info "$file" | grep 'Architecture' | awk '{print $2}')
+            jfrog rt upload "$file" "$ARTIFACTORY_DEB_DEV/$PACKAGE_NAME/$PACKAGE_VERSION/$(basename $file)" \
+            --build-name=$PACKAGE_NAME-deb \
+            --build-number=$PACKAGE_VERSION \
+            --target-props "deb.distribution=stable;deb.component=main;deb.architecture=${arch}" \
+            --deb "stable/main/${arch}"
+          done
+
+          jfrog rt build-collect-env "$PACKAGE_NAME-deb" "$PACKAGE_VERSION"
+          jfrog rt build-add-git  "$PACKAGE_NAME-deb" "$PACKAGE_VERSION"
+          jfrog rt build-publish  "$PACKAGE_NAME-deb" "$PACKAGE_VERSION"
+
   build-docker-image:
     needs:
       - create-release
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     outputs:
       image_version: ${{ steps.metadata.outputs.IMAGE_VERSION }}
     steps:
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3.11.0
       - name: Checkout Code
-        uses: actions/checkout@v4
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
           fetch-depth: 1
       - name: Get Metadata
@@ -84,14 +262,14 @@ jobs:
           echo "IMAGE_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
 
       - name: Login to JFrog
-        uses: jfrog/setup-jfrog-cli@v4
+        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
         env:
           JF_URL: ${{ vars.ARTIFACTORY_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
           JF_PROJECT: ${{ vars.JFROG_CLI_BUILD_PROJECT }}
 
       - name: Login to JFrog Artifactory
-        uses: docker/login-action@v3
+        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
         with:
           registry: aerospike.jfrog.io
           username: ${{ secrets.ARTIFACTORY_USER }}
